version: "3.2"
services:
  php:
    build: 
      context: .
    image: leandrorc/myphp
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysqld
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mypass
      - MYSQL_DB=miphp
    volumes:
      -  /var/www/html/
    ports:
      - "30001:80"
    container_name: php-app
  mysqld:
    image: leandrorc/mysqldata:v2
   
    networks:
      - backend
    
       
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    depends_on:
      - mysqld
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysqld
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend:
